version: "3.9"

services:
  mongo:
    image: mongo:8.2.6-rc0
    container_name: ticket-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234

  redis:
    image: redis:8.6.1
    container_name: ticket-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    container_name: ticket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin1234

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
